int toneDuration = 50 ;
int speakPin = 12 ;
int tones[] = { 262,294,330,349,392,440,494};
void setup () {
}
void loop () {
  tone(speakPin,tones[0],toneDuration);
////  delay (1000);
//  tone(speakPin,tones[0],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[0],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[4],toneDuration);
//  delay(1000); 
//  tone(speakPin,tones[2],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[2],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[2],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[0],toneDuration);
//  delay(1000); 
//  tone(speakPin,tones[0],toneDuration);
////  delay(1000);   
//  tone(speakPin,tones[2],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[4],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[4],toneDuration);
//  delay(1000); 
//  tone(speakPin,tones[3],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[2],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[1],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[1],toneDuration);
//  delay(1000); 
//  tone(speakPin,tones[1],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[2],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[3],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[3],toneDuration);
//  delay(1000); 
//  tone(speakPin,tones[2],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[1],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[2],toneDuration);
////  delay(1000); 
//  tone(speakPin,tones[0],toneDuration);
//  delay(1000); 
//  tone(speakPin,tones[0],toneDuration); 
////  delay(1000); 
//  tone(speakPin,tones[2],toneDuration); 
////  delay(1000); 
//  tone(speakPin,tones[1],toneDuration);   
////  delay(1000); 
//  tone(speakPin,tones[4],toneDuration);
//  delay(1000);  
//  tone(speakPin,tones[6],toneDuration);  
////  delay(1000);  
//  tone(speakPin,tones[1],toneDuration); 
////  delay(1000); 
//  tone(speakPin,tones[0],toneDuration);   
////  delay(1000); 
//  tone(speakPin,tones[0],toneDuration);
//  delay(1000);
}
